import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import { test } from "node:test";
import { verifyPreviewToken } from "../dist/preview/verifyPreviewToken.js";
import {
  handleCloakWpRequest,
} from "../dist/rest/handleCloakWpRequest.js";
import {
  parseRevalidationBody,
} from "../dist/revalidation/request.js";

const secret = "correct horse battery staple";
const phpToken =
  "eyJwcmV2aWV3S2V5IjoiYmxvY2tfYWJjMTIzIiwicGF0aG5hbWUiOiJcL3dvcmtcL2NhZlx1MDBlOSIsImV4cCI6MTg5MzQ1NjAwMH0.dr31mmK_ihlJ_yGCoObriAZiXy6N6mMGn_3q-gO-WFY";

function requestOptions(overrides = {}) {
  return {
    route: ["revalidate"],
    secret,
    revalidatePath: () => {},
    scheduleCacheWarming: () => {},
    enablePreviewMode: () => {},
    exitPreviewMode: () => {},
    ...overrides,
  };
}

function signPreviewToken(payload) {
  const encodedPayload = Buffer.from(JSON.stringify(payload)).toString("base64url");
  const signature = createHmac("sha256", secret)
    .update(encodedPayload)
    .digest("base64url");
  return `${encodedPayload}.${signature}`;
}

test("verifies a fixed token generated by PHP hash_hmac", async () => {
  const result = await verifyPreviewToken(phpToken, secret, {
    now: 1_893_455_000_000,
  });

  assert.deepEqual(result, {
    valid: true,
    payload: {
      previewKey: "block_abc123",
      pathname: "/work/café",
      exp: 1_893_456_000,
    },
  });
});

test("rejects modified and expired preview tokens", async () => {
  const modified = `${phpToken.slice(0, -1)}A`;
  assert.equal(
    (await verifyPreviewToken(modified, secret)).error,
    "invalid-signature",
  );
  assert.equal(
    (
      await verifyPreviewToken(phpToken, secret, {
        now: 1_893_456_031_000,
        clockSkewSeconds: 30,
      })
    ).error,
    "expired-token",
  );
});

test("parses, normalizes, and deduplicates revalidation paths", () => {
  assert.deepEqual(
    parseRevalidationBody(
      JSON.stringify({
        paths: ["/", "/work/", "/work", "/bad?query=1", 42],
      }),
    ),
    {
      valid: true,
      paths: ["/", "/work"],
      invalidResults: [
        {
          path: "/bad?query=1",
          status: "invalid",
          error:
            "Path must be a canonical absolute pathname without a query or hash.",
        },
        {
          path: "42",
          status: "invalid",
          error:
            "Path must be a canonical absolute pathname without a query or hash.",
        },
      ],
    },
  );
});

test("requires authenticated POST revalidation", async () => {
  const unauthenticated = await handleCloakWpRequest(
    new Request("https://site.test/api/cloakwp/revalidate", {
      method: "POST",
      body: JSON.stringify({ paths: ["/"] }),
    }),
    requestOptions(),
  );
  assert.equal(unauthenticated.status, 401);

  const wrongMethod = await handleCloakWpRequest(
    new Request("https://site.test/api/cloakwp/revalidate"),
    requestOptions(),
  );
  assert.equal(wrongMethod.status, 405);
});

test("revalidates unique paths and reports per-path errors", async () => {
  const revalidated = [];
  const warmed = [];
  const body = JSON.stringify({
    paths: ["/", "/work/", "/work", "/bad#hash", "/fails"],
  });
  const response = await handleCloakWpRequest(
    new Request("https://site.test/api/cloakwp/revalidate", {
      method: "POST",
      headers: { Authorization: `Bearer ${secret}` },
      body,
    }),
    requestOptions({
      revalidatePath(path) {
        if (path === "/fails") throw new Error("cache unavailable");
        revalidated.push(path);
      },
      scheduleCacheWarming(paths) {
        warmed.push(...paths);
      },
    }),
  );

  assert.equal(response.status, 207);
  assert.deepEqual(revalidated, ["/", "/work"]);
  assert.deepEqual(warmed, ["/", "/work"]);
});

test("accepts PHP-compatible timestamped body signatures", async () => {
  const body = JSON.stringify({ paths: ["/signed"] });
  const timestamp = "1893455000";
  const signature = createHmac("sha256", secret)
    .update(`${timestamp}.${body}`)
    .digest("hex");
  const response = await handleCloakWpRequest(
    new Request("https://site.test/api/cloakwp/revalidate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-CloakWP-Timestamp": timestamp,
        "X-CloakWP-Signature": `sha256=${signature}`,
      },
      body,
    }),
    requestOptions({ now: 1_893_455_000_000 }),
  );

  assert.equal(response.status, 200);
});

test("post previews require a token bound to the post and pathname", async () => {
  const previewModes = [];
  const pathname = "/work/example";
  const token = signPreviewToken({
    previewKey: "post-42",
    pathname,
    exp: 1_893_456_000,
  });
  const response = await handleCloakWpRequest(
    new Request(
      `https://site.test/api/cloakwp/preview?token=${encodeURIComponent(token)}&pathname=${encodeURIComponent(pathname)}&postId=42&revisionId=43&postType=portfolio`,
    ),
    requestOptions({
      route: ["preview"],
      now: 1_893_455_000_000,
      enablePreviewMode(input) {
        previewModes.push(input);
      },
    }),
  );

  assert.equal(response.status, 307);
  assert.equal(response.headers.get("location"), pathname);
  assert.equal(previewModes[0].data.postId, "42");

  const mismatched = await handleCloakWpRequest(
    new Request(
      `https://site.test/api/cloakwp/preview?token=${encodeURIComponent(token)}&pathname=${encodeURIComponent(pathname)}&postId=99&postType=portfolio`,
    ),
    requestOptions({ route: ["preview"], now: 1_893_455_000_000 }),
  );
  assert.equal(mismatched.status, 401);
});

test("is-authenticated is removed", async () => {
  const response = await handleCloakWpRequest(
    new Request("https://site.test/api/cloakwp/is-authenticated"),
    requestOptions({ route: ["is-authenticated"] }),
  );
  assert.equal(response.status, 404);
});

test("password grant sets httpOnly session cookies and redirects to establish-session", async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async (input, init) => {
    assert.equal(String(input), "https://wp.test/wp-json/cloakwp/auth/authorize");
    assert.equal(init.headers["X-CloakWP-Secret"], "session-secret");
    const body = JSON.parse(init.body);
    assert.equal(body.grant_type, "password");
    return new Response(
      JSON.stringify({
        accessToken: "access-token",
        accessTokenExpiration: Math.floor(Date.now() / 1000) + 900,
        refreshToken: "refresh-token",
        refreshTokenExpiration: Math.floor(Date.now() / 1000) + 1209600,
        wpLoginCode: "login-code",
      }),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  };

  try {
    const response = await handleCloakWpRequest(
      new Request("https://site.test/api/cloakwp/auth/authorize", {
        method: "POST",
        headers: {
          Origin: "https://site.test",
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: "grant_type=password&username=ed&password=secret&redirect=/",
      }),
      requestOptions({
        route: ["auth", "authorize"],
        session: {
          wordpressUrl: "https://wp.test",
          secret: "session-secret",
        },
      }),
    );

    assert.equal(response.status, 302);
    assert.match(
      response.headers.get("location"),
      /^https:\/\/wp\.test\/wp-json\/cloakwp\/auth\/establish-session\?code=login-code/,
    );
    const cookies = response.headers.getSetCookie();
    assert.ok(cookies.some((cookie) => cookie.startsWith("cloakwp_at=access-token") && cookie.includes("HttpOnly")));
    assert.ok(cookies.some((cookie) => cookie.startsWith("cloakwp_rt=refresh-token") && cookie.includes("HttpOnly")));
    assert.ok(cookies.some((cookie) => cookie.startsWith("cloakwp_ui=1") && !cookie.includes("HttpOnly")));
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test("authorize POST rejects a cross-origin request", async () => {
  const response = await handleCloakWpRequest(
    new Request("https://site.test/api/cloakwp/auth/authorize", {
      method: "POST",
      headers: {
        Origin: "https://evil.test",
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: "grant_type=password&username=ed&password=secret",
    }),
    requestOptions({
      route: ["auth", "authorize"],
      session: { wordpressUrl: "https://wp.test", secret: "session-secret" },
    }),
  );
  assert.equal(response.status, 403);
});

test("wp-admin handler 302s to establish-session", async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () =>
    new Response(
      JSON.stringify({
        accessToken: "access-token",
        accessTokenExpiration: Math.floor(Date.now() / 1000) + 900,
        refreshToken: "refresh-token",
        refreshTokenExpiration: Math.floor(Date.now() / 1000) + 1209600,
        wpLoginCode: "fresh-code",
      }),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );

  try {
    const response = await handleCloakWpRequest(
      new Request(
        "https://site.test/api/cloakwp/auth/wp-admin?path=%2Fwp-admin%2Fedit.php",
        { headers: { cookie: "cloakwp_rt=existing-refresh" } },
      ),
      requestOptions({
        route: ["auth", "wp-admin"],
        session: { wordpressUrl: "https://wp.test", secret: "session-secret" },
      }),
    );

    assert.equal(response.status, 302);
    const location = new URL(response.headers.get("location"));
    assert.equal(
      location.origin + location.pathname,
      "https://wp.test/wp-json/cloakwp/auth/establish-session",
    );
    assert.equal(location.searchParams.get("code"), "fresh-code");
    assert.equal(
      location.searchParams.get("redirect"),
      "https://wp.test/wp-admin/edit.php",
    );
  } finally {
    globalThis.fetch = originalFetch;
  }
});
